services:
  account-service-redis:
    image: redis:alpine
    container_name: account-service-redis
    ports:
      - 6379:6379
    volumes:
      - account-service-redis-data:/data
    profiles: [development]
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  account-service-redis-test:
    image: redis:alpine
    container_name: account-service-redis-test
    ports:
      - 6380:6379
    volumes:
      - account-service-redis-test-data:/data
    profiles: [test, ci]
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  account-service-mongo:
    image: mongo
    command: mongod --port 27017
    container_name: account-service-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - account-service-mongo-data:/data/db
      - account-service-mongo-config:/data/configdb
    profiles: [development]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--port',
          '27017',
          '--eval',
          'db.adminCommand("ping")',
        ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  account-service-mongo-express:
    image: mongo-express
    container_name: account-service-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://account-service-mongo:27017
    depends_on:
      - account-service-mongo
    profiles: [development]

  account-service-mongo-test:
    image: mongo
    command: mongod --port 27018
    container_name: account-service-mongo-test
    restart: always
    ports:
      - 27018:27018
    volumes:
      - account-service-mongo-test-data:/data/db
      - account-service-mongo-test-config:/data/configdb
    profiles: [test, ci]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--port',
          '27018',
          '--eval',
          'db.adminCommand("ping")',
        ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  account-service-mongo-test-express:
    image: mongo-express
    container_name: account-service-mongo-test-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://account-service-mongo-test:27018
    depends_on:
      - account-service-mongo-test
    profiles: [test]

  message-service-mongo:
    image: mongo
    command: mongod --port 27019
    container_name: message-service-mongo
    ports:
      - 27019:27019
    volumes:
      - message-service-mongo-data:/data/db
      - message-service-mongo-config:/data/configdb
    profiles: [development]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--port',
          '27019',
          '--eval',
          'db.adminCommand("ping")',
        ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  message-service-mongo-express:
    image: mongo-express
    container_name: message-service-mongo-express
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://message-service-mongo:27019
    depends_on:
      - message-service-mongo
    profiles: [development]

  message-service-mongo-test:
    image: mongo
    command: mongod --port 27020
    container_name: message-service-mongo-test
    restart: always
    ports:
      - 27020:27020
    volumes:
      - message-service-mongo-test-data:/data/db
      - message-service-mongo-test-config:/data/configdb
    profiles: [test, ci]
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          '--port',
          '27020',
          '--eval',
          'db.adminCommand("ping")',
        ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  message-service-mongo-test-express:
    image: mongo-express
    container_name: message-service-mongo-test-express
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://message-service-mongo-test:27020
    depends_on:
      - message-service-mongo-test
    profiles: [test]

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    profiles: [development]
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  rabbitmq-test:
    image: 'rabbitmq:management-alpine'
    container_name: rabbitmq-test
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - rabbitmq-test:/var/lib/rabbitmq
    profiles: [test, ci]
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

volumes:
  account-service-redis-data:
  account-service-redis-test-data:
  account-service-mongo-data:
  account-service-mongo-config:
  account-service-mongo-test-data:
  account-service-mongo-test-config:
  message-service-mongo-data:
  message-service-mongo-config:
  message-service-mongo-test-data:
  message-service-mongo-test-config:
  rabbitmq:
  rabbitmq-test:
