services:
  account-service-mongo:
    image: mongo
    container_name: account-service-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - account-service-mongo-data:/data/db
      - account-service-mongo-config:/data/configdb

  account-service-mongo-test:
    image: mongo
    container_name: account-service-mongo-test
    restart: always
    ports:
      - 27019:27017

  account-service-mongo-express:
    image: mongo-express
    container_name: account-service-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://account-service-mongo:27017
    depends_on:
      - account-service-mongo

  message-service-mongo:
    image: mongo
    command: mongod --port 27018
    container_name: message-service-mongo
    ports:
      - 27018:27018
    volumes:
      - message-service-mongo-data:/data/db
      - message-service-mongo-config:/data/configdb

  message-service-mongo-test:
    image: mongo
    container_name: message-service-mongo-test
    restart: always
    ports:
      - 27020:27017

  message-service-mongo-express:
    image: mongo-express
    container_name: message-service-mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://message-service-mongo:27018
    depends_on:
      - message-service-mongo

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  account-service-mongo-data:
  account-service-mongo-config:
  message-service-mongo-data:
  message-service-mongo-config:
  rabbitmq_data:
