name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [23.1.0]
    env:
      ACCOUNT_SERVICE_API_KEY: ${{ secrets.ACCOUNT_SERVICE_API_KEY }}
      ACCOUNT_SERVICE_FACEBOOK_CLIENT_SECRET: ${{ secrets.ACCOUNT_SERVICE_FACEBOOK_CLIENT_SECRET }}
      ACCOUNT_SERVICE_GOOGLE_CLIENT_SECRET: ${{ secrets.ACCOUNT_SERVICE_GOOGLE_CLIENT_SECRET }}
      ACCOUNT_SERVICE_JWT_SECRET: ${{ secrets.ACCOUNT_SERVICE_JWT_SECRET }}
      MESSAGE_SERVICE_ACCOUNT_SERVICE_API_KEY: ${{ secrets.MESSAGE_SERVICE_ACCOUNT_SERVICE_API_KEY }}
      MESSAGE_SERVICE_JWT_SECRET: ${{ secrets.MESSAGE_SERVICE_JWT_SECRET }}
      ACCOUNT_SERVICE_FACEBOOK_CLIENT_ID: ${{ vars.ACCOUNT_SERVICE_FACEBOOK_CLIENT_ID }}
      ACCOUNT_SERVICE_FILE_STORAGE_SERVICE_MAX_FILE_SIZE: ${{ vars.ACCOUNT_SERVICE_FILE_STORAGE_SERVICE_MAX_FILE_SIZE }}
      ACCOUNT_SERVICE_FILE_STORAGE_SERVICE_URL: ${{ vars.ACCOUNT_SERVICE_FILE_STORAGE_SERVICE_URL }}
      ACCOUNT_SERVICE_FRONT_END_URL: ${{ vars.ACCOUNT_SERVICE_FRONT_END_URL }}
      ACCOUNT_SERVICE_GOOGLE_CLIENT_ID: ${{ vars.ACCOUNT_SERVICE_GOOGLE_CLIENT_ID }}
      ACCOUNT_SERVICE_JWT_AUDIENCE: ${{ vars.ACCOUNT_SERVICE_JWT_AUDIENCE }}
      ACCOUNT_SERVICE_JWT_EXPIRATION_TIME_IN_SECONDS: ${{ vars.ACCOUNT_SERVICE_JWT_EXPIRATION_TIME_IN_SECONDS }}
      ACCOUNT_SERVICE_JWT_ISSUER: ${{ vars.ACCOUNT_SERVICE_JWT_ISSUER }}
      ACCOUNT_SERVICE_LOG_LEVEL: ${{ vars.ACCOUNT_SERVICE_LOG_LEVEL }}
      ACCOUNT_SERVICE_MONGO_URI: ${{ vars.ACCOUNT_SERVICE_MONGO_URI }}
      ACCOUNT_SERVICE_PORT: ${{ vars.ACCOUNT_SERVICE_PORT }}
      ACCOUNT_SERVICE_RABBIT_MQ_EXCHANGE_NAME: ${{ vars.ACCOUNT_SERVICE_RABBIT_MQ_EXCHANGE_NAME }}
      ACCOUNT_SERVICE_RABBIT_MQ_URL: ${{ vars.ACCOUNT_SERVICE_RABBIT_MQ_URL }}
      ACCOUNT_SERVICE_REDIS_URL: ${{ vars.ACCOUNT_SERVICE_REDIS_URL }}
      MESSAGE_SERVICE_ACCOUNT_SERVICE_URL: ${{ vars.MESSAGE_SERVICE_ACCOUNT_SERVICE_URL }}
      MESSAGE_SERVICE_JWT_AUDIENCE: ${{ vars.MESSAGE_SERVICE_JWT_AUDIENCE }}
      MESSAGE_SERVICE_JWT_EXPIRATION_TIME_IN_SECONDS: ${{ vars.MESSAGE_SERVICE_JWT_EXPIRATION_TIME_IN_SECONDS }}
      MESSAGE_SERVICE_JWT_ISSUER: ${{ vars.MESSAGE_SERVICE_JWT_ISSUER }}
      MESSAGE_SERVICE_LOG_LEVEL: ${{ vars.MESSAGE_SERVICE_LOG_LEVEL }}
      MESSAGE_SERVICE_MONGO_URI: ${{ vars.MESSAGE_SERVICE_MONGO_URI }}
      MESSAGE_SERVICE_PORT: ${{ vars.MESSAGE_SERVICE_PORT }}
      MESSAGE_SERVICE_WEB_SOCKET_SERVER_PORT: ${{ vars.MESSAGE_SERVICE_WEB_SOCKET_SERVER_PORT }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
